version: '3'
services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - 7777:27017
    restart: always
    environment:
      - MONGODB_CONTAINER_NAME=mongodb

  automobile:
    build: ./app
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    environment:
      - MONGODB_CONTAINER_NAME=mongodb


