openapi: 3.0.2
info:
  title: FastAPI
  version: 0.1.0
paths:
  /cars/{car_id}:
    get:
      summary: Get Car Details
      operationId: get_car_details_cars__car_id__get
      parameters:
        - required: true
          schema:
            title: Car Id
            type: string
          name: car_id
          in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    put:
      summary: Update Car Details
      operationId: update_car_details_cars__car_id__put
      parameters:
        - required: true
          schema:
            title: Car Id
            type: string
          name: car_id
          in: path
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModifiedCar'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    delete:
      summary: Delete Car Details
      operationId: delete_car_details_cars__car_id__delete
      parameters:
        - required: true
          schema:
            title: Car Id
            type: string
          name: car_id
          in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /cars:
    get:
      summary: Get All Car Details
      operationId: get_all_car_details_cars_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
    post:
      summary: Add Car Details
      operationId: add_car_details_cars_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cars'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    Cars:
      title: Cars
      required:
        - VIN
        - plate
        - state
        - Model
        - owner_name
        - owner_Address
        - owner_DL
        - problem_description
        - date_in
        - date_out
        - technician
        - city
        - Zipcode
        - shop
      type: object
      properties:
        VIN:
          title: Vin
          type: string
        plate:
          title: Plate
          type: string
        state:
          title: State
          type: string
        Model:
          title: Model
          type: integer
        owner_name:
          title: Owner Name
          type: string
        owner_Address:
          title: Owner Address
          type: string
        owner_DL:
          title: Owner Dl
          type: string
        problem_description:
          title: Problem Description
          type: string
        date_in:
          title: Date In
          type: string
        date_out:
          title: Date Out
          type: string
        technician:
          title: Technician
          type: string
        city:
          title: City
          type: string
        Zipcode:
          title: Zipcode
          type: integer
        shop:
          $ref: '#/components/schemas/Shop'
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    ModifiedCar:
      title: ModifiedCar
      type: object
      properties:
        VIN:
          title: Vin
          type: string
        plate:
          title: Plate
          type: string
        state:
          title: State
          type: string
        Model:
          title: Model
          type: integer
        owner_name:
          title: Owner Name
          type: string
        owner_Address:
          title: Owner Address
          type: string
        owner_DL:
          title: Owner Dl
          type: string
        problem_description:
          title: Problem Description
          type: string
        date_in:
          title: Date In
          type: string
        date_out:
          title: Date Out
          type: string
        technician:
          title: Technician
          type: string
        city:
          title: City
          type: string
        Zipcode:
          title: Zipcode
          type: integer
    Shop:
      title: Shop
      required:
        - shopId
        - name
        - city
        - state
      type: object
      properties:
        shopId:
          title: Shopid
          maximum: 48
          minimum: 0
          type: integer
        name:
          title: Name
          type: string
        city:
          title: City
          type: string
        state:
          title: State
          type: string
    ValidationError:
      title: ValidationError
      required:
        - loc
        - msg
        - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
              - type: string
              - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
